apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: jwt-websocket-integration
spec:
  selector:
    matchLabels:
      app: imv
      component: websocket-integration
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals:
              - '*'
    - from:
        - source:
            notRequestPrincipals:
              - '*'
      to:
        - operation:
            paths:
              - /websocket-integration/swagger-ui.html
