apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appname }}
    component: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.dc.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      component: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        component: {{ .Release.Name }}
        version:  {{ .Chart.Version }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        {{- if .Values.dc.env_vars.enabled }}
        env:
          {{- toYaml .Values.dc.env_vars.data | nindent 8 }}
        {{- end}}
        image: image-registry.openshift-image-registry.svc:5000/cicd/taskapp:latest
        ports:
        - containerPort: {{ .Values.service.port }}
          protocol: TCP
        - containerPort: {{ .Values.service.port_ssl }}
          protocol: TCP
        resources:
          {{- toYaml .Values.dc.resources | nindent 10 }}
        terminationMessagePath: "/dev/termination-log"
        volumeMounts:
          {{- if .Values.configmap.app.enabled }}
          - mountPath: {{ .Values.configmap.app.mountPath }}
            name: {{ .Release.Name }}-config
            subPath: {{ .Values.configmap.app.subPath }}
          {{- end }}
          {{- if .Values.configmap.logback.enabled }}
          - mountPath: {{ .Values.configmap.logback.mountPath }}
            name: {{ .Release.Name }}-logback
            subPath: {{ .Values.configmap.logback.subPath }}
          {{- end }}
          {{- if .Values.secret.trustore.enabled }}
          - name: {{ .Values.secret.trustore.name }}
            mountPath: {{ .Values.secret.trustore.mountPath }}
            subPath: {{ .Values.secret.trustore.subPath }}
          {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        {{- if .Values.configmap.app.enabled }}
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-config
        {{- end }}
        {{- if .Values.configmap.logback.enabled }}
        - name: {{ .Release.Name }}-logback
          configMap:
            name: {{ .Release.Name }}-logback
        {{- end }}
        {{- if .Values.secret.trustore.enabled }}
        - name: {{ .Values.secret.trustore.name }}
          secret:
            defaultMode: 420
            secretName: {{ .Values.secret.trustore.name }}
        {{- end }}
