{{- if .Values.secret.app.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.app.name }}
  labels:
    app: {{ .Values.appname }}
type: Opaque 
data:
  {{- toYaml .Values.secret.app.data | nindent 2 }}
{{- end}}