apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appname }}-private-{{ .Release.Name }}
  labels:
    app: {{ .Values.appname }}
    component: {{ .Release.Name }}
spec:
  hosts:
  - "{{ .Values.virtualservicepri.hosts }}"
  gateways:
  - {{ .Values.appname }}-private-api-gateway
  http:
  - match:
    - uri:
        prefix: /{{ .Release.Name }}/
    - uri:
        exact: /{{ .Release.Name }}
    route:
    - destination:
        host: {{ .Release.Name }}
        port:
          number: {{ .Values.service.port }}
