{{- if .Values.configmap.app.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Values.appname }}
data:
  {{- toYaml .Values.configmap.app.data | nindent 2 }}
{{- end }}