{{- if .Values.configmap.logback.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-logback
  labels:
    app: {{ .Values.appname }}
data:
  {{- toYaml .Values.configmap.logback.data | nindent 2 }}
{{- end }}