apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appname }}-api-{{ .Release.Name }}
  labels:
    app: {{ .Values.appname }}
    component: {{ .Release.Name }}
spec:
  hosts:
  - "{{ .Values.virtualserviceapi.hosts }}"
  gateways:
  - {{ .Values.appname }}-api-gateway
  http:
  - match:
    - uri:
        prefix: /{{ .Release.Name }}/public/
    - uri:
        exact: /{{ .Release.Name }}/public
    route:
    - destination:
        host: {{ .Release.Name }}
        port:
          number: {{ .Values.service.port }}
